// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9cLUOLJRN8Iu8cSrUmQaKgcr2f9F7d-U',
    appId: '1:669858546192:web:52082481e1363f6a5cc095',
    messagingSenderId: '669858546192',
    projectId: 'geospatial-commute-sharing-app',
    authDomain: 'geospatial-commute-sharing-app.firebaseapp.com',
    storageBucket: 'geospatial-commute-sharing-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDt_7xPZzr_KVJSTAdGts2MMXmlE-T7dXM',
    appId: '1:669858546192:android:46fb4240e5897e4d5cc095',
    messagingSenderId: '669858546192',
    projectId: 'geospatial-commute-sharing-app',
    storageBucket: 'geospatial-commute-sharing-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMQCj_cyhWKRHd9mH6lzun2b0QBGU_lcg',
    appId: '1:669858546192:ios:c55a31e6635b1e985cc095',
    messagingSenderId: '669858546192',
    projectId: 'geospatial-commute-sharing-app',
    storageBucket: 'geospatial-commute-sharing-app.firebasestorage.app',
    androidClientId: '669858546192-tt4pq3hpbiki6r19jir81hfqio3kbs66.apps.googleusercontent.com',
    iosClientId: '669858546192-r6fgd7t10fpi49rp7e412h5ag3toukuh.apps.googleusercontent.com',
    iosBundleId: 'com.example.geoSpatialRidePoolingSystem2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMQCj_cyhWKRHd9mH6lzun2b0QBGU_lcg',
    appId: '1:669858546192:ios:c55a31e6635b1e985cc095',
    messagingSenderId: '669858546192',
    projectId: 'geospatial-commute-sharing-app',
    storageBucket: 'geospatial-commute-sharing-app.firebasestorage.app',
    androidClientId: '669858546192-tt4pq3hpbiki6r19jir81hfqio3kbs66.apps.googleusercontent.com',
    iosClientId: '669858546192-r6fgd7t10fpi49rp7e412h5ag3toukuh.apps.googleusercontent.com',
    iosBundleId: 'com.example.geoSpatialRidePoolingSystem2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9cLUOLJRN8Iu8cSrUmQaKgcr2f9F7d-U',
    appId: '1:669858546192:web:f75cf5270fd4240e5cc095',
    messagingSenderId: '669858546192',
    projectId: 'geospatial-commute-sharing-app',
    authDomain: 'geospatial-commute-sharing-app.firebaseapp.com',
    storageBucket: 'geospatial-commute-sharing-app.firebasestorage.app',
  );

}